### ISSUE TITLE
Failed to read memory at address [XXX] for [YYY]. Error code: 12b

### ISSUE THREAD

**Issue by curious-city** [mschoenbein/Warenrechner-Client-Venedig-History-Edition#1]
![Screenshot](https://github.com/user-attachments/assets/a324719e-2140-41bd-bb8f-77f1e894bc28)

Tested on Anno 1404 Venice (History Collection) v.4.00.4253/1.4514.940870
-> Using Warenrechner: *Neu 14.09.2024* (thanks for that btw)

Tested with starting "WarenrechnerClientVenedigHistoryEdition.exe" before as well as after Anno was started, both with same result.
Tested with admin privileges as well, still same.
Tested with a map including no people and tested with a map including thousands of people, same result.

Not sure if I'm doing anything wrong or if it is a bug. I'm just leaving this here in case it is.

**Comment by mschoenbein** [comment]
Hey, can you please check the version of the Anno Addon EXE (located directly in the root directory)? To read the memory, the version must be 1:1. The client is for version 4.0.4253.0. Are you using the German version?

![Screenshot 2024-12-17 114651](https://github.com/user-attachments/assets/aea4e39c-3b2a-4d16-9e4a-8bafeef8e45b)

**Comment by curious-city** [comment]
I'm using the exact same version. I play the german version but english is included.
![Anno_1404_Addon_Version_Screenshot](https://github.com/user-attachments/assets/a932419f-991c-4269-ad83-8e1137c2b83a)

**Comment by mschoenbein** [comment]
Is it perhaps the Steam version? I'm wondering because the file size is different.

**Comment by curious-city** [comment]
That is actually a good question. Whenever I reinstall the game on a new system I copy all the old files from the previous instance over the new one so I don't lose all my settings and those old files go back at least 4 years (before History Edition was a thing).
-> To test I would have to reinstall the game once again which I don't really want to do at the moment.

So I guess those file discrepancies could be the problem here although it is kinda weird that the file size of the .exe-file is determining the function of your tool. The location where the data is stored in memory should not be affected by the .exe-file, shouldn't it?
Or is it a different problem than finding the memory location?

**Comment by mschoenbein** [comment]
Ah okay, that's the problem. The pointers (memory addresses) change as soon as the EXE is recompiled. This means you either have to have exactly the same version (the client is for the current version via the UBI Lauchner) or you have to look for the pointers again for the respective EXE.

**Comment by curious-city** [comment]
Oh that is interesting, I didn't know that. Thanks!

**Comment by mschoenbein** [comment]
Yes, sorry, I hope there is a way for you to update to the latest version. I am closing this topic. Greetings!
